import type { IdolMember } from "../scene/createChibiIdol";

/** Stage capacity of the idol line-up; the HUD lets the player show 1..MAX. */
export const MAX_IDOL_COUNT = 12;

/**
 * Twelve-member Little Weekend atlas. Shared slim-chibi skeleton; members
 * read apart through hair, wardrobe, and palette.
 */
export const IDOL_MEMBERS: readonly IdolMember[] = [
  {
    name: "Rosie",
    hairStyle: "twintails",
    outfit: "classic",
    sleeve: "puff",
    main: "#dc7895",
    accent: "#ffe4ce",
    trim: "#aa465e",
    hair: "#754633",
    hairLight: "#925b42",
    skin: "#efbc9b",
    socks: "#fff4e7",
    shoes: "#a94b68",
    height: 1,
  },
  {
    name: "Mimi",
    hairStyle: "bob",
    outfit: "sailor",
    sleeve: "short",
    main: "#8ab9aa",
    accent: "#fff3d9",
    trim: "#397a73",
    hair: "#45665e",
    hairLight: "#5b8172",
    skin: "#f1c5a8",
    socks: "#f6ebdb",
    shoes: "#477971",
    height: 0.97,
  },
  {
    name: "Sunny",
    hairStyle: "ponytail",
    outfit: "sport",
    sleeve: "short",
    main: "#efbb54",
    accent: "#fff3d9",
    trim: "#ce763e",
    hair: "#bf813b",
    hairLight: "#d89d50",
    skin: "#bd805c",
    socks: "#fff3dc",
    shoes: "#d49436",
    height: 1.03,
  },
  {
    name: "Lulu",
    hairStyle: "buns",
    outfit: "ballet",
    sleeve: "puff",
    main: "#b59acb",
    accent: "#f7e3ee",
    trim: "#81669e",
    hair: "#9480ad",
    hairLight: "#af98c4",
    skin: "#ecc2af",
    socks: "#f3e5eb",
    shoes: "#9875ae",
    height: 0.96,
  },
  {
    name: "Aster",
    hairStyle: "long",
    outfit: "celestial",
    sleeve: "bell",
    main: "#647faa",
    accent: "#e8dca8",
    trim: "#3f567d",
    hair: "#d6d5df",
    hairLight: "#efedf1",
    skin: "#e7b294",
    socks: "#dce1ed",
    shoes: "#415982",
    height: 1.05,
  },
  {
    name: "Peony",
    hairStyle: "sidebraid",
    outfit: "cottage",
    sleeve: "puff",
    main: "#df9b7c",
    accent: "#fff0d2",
    trim: "#a7604e",
    hair: "#ad593e",
    hairLight: "#c8754d",
    skin: "#efbb96",
    socks: "#fff0d8",
    shoes: "#9d634c",
    height: 0.99,
  },
  {
    name: "Rumi",
    hairStyle: "waves",
    outfit: "rock",
    sleeve: "long",
    main: "#98556d",
    accent: "#eac8ce",
    trim: "#433849",
    hair: "#4d354c",
    hairLight: "#71516b",
    skin: "#c48e70",
    socks: "#554253",
    shoes: "#403543",
    height: 1.02,
  },
  {
    name: "Nova",
    hairStyle: "pixie",
    outfit: "future",
    sleeve: "long",
    main: "#d4dce0",
    accent: "#b9d9cc",
    trim: "#687e8a",
    hair: "#adb9c3",
    hairLight: "#d8e0e5",
    skin: "#a96f53",
    socks: "#e4e9e6",
    shoes: "#8298a0",
    height: 1,
  },
  {
    name: "Aqua",
    hairStyle: "sidepony",
    outfit: "bubble",
    sleeve: "cap",
    main: "#6aafb0",
    accent: "#f6dab0",
    trim: "#347d89",
    hair: "#387e85",
    hairLight: "#569fa0",
    skin: "#e9ae8e",
    socks: "#f9ecd7",
    shoes: "#478e98",
    height: 0.98,
  },
  {
    name: "Coco",
    hairStyle: "braids",
    outfit: "academy",
    sleeve: "long",
    main: "#b89a56",
    accent: "#f6e7cd",
    trim: "#6f5740",
    hair: "#553b2c",
    hairLight: "#79513a",
    skin: "#d19a75",
    socks: "#f1e2ca",
    shoes: "#6c503d",
    height: 0.97,
  },
  {
    name: "Cherry",
    hairStyle: "curls",
    outfit: "retro",
    sleeve: "short",
    main: "#d77668",
    accent: "#ffe5cc",
    trim: "#a54c47",
    hair: "#8d4134",
    hairLight: "#b65b43",
    skin: "#f0c4a4",
    socks: "#ffeada",
    shoes: "#aa4f49",
    height: 0.99,
  },
  {
    name: "Yuna",
    hairStyle: "hime",
    outfit: "royal",
    sleeve: "bell",
    main: "#505875",
    accent: "#dabb78",
    trim: "#a35f73",
    hair: "#292c3e",
    hairLight: "#41465e",
    skin: "#e8b899",
    socks: "#efe0d1",
    shoes: "#4a4966",
    height: 1.04,
  },
];
